# Generated by Django 4.1.3 on 2024-11-14 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RoomModel',
            fields=[
                ('mongo_id', models.CharField(max_length=24, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('type', models.CharField(max_length=100)),
                ('theme', models.JSONField()),
                ('colorscheme', models.JSONField()),
                ('image', models.ImageField(upload_to='home/pics/')),
            ],
        ),
    ]
